import { expect, test, type Page } from '@playwright/test'

async function openPlacement(page: Page) { await page.goto('./#/placement'); await expect(page.getByRole('heading', { name: 'Point at production' })).toBeVisible() }
async function command(page: Page, tokens: string[]) { await page.waitForTimeout(75); for (const token of tokens) { if (token === '<Esc>') await page.keyboard.press('Escape'); else if (token === '<Enter>') await page.keyboard.press('Enter'); else if (token.length === 1) await page.keyboard.press(token); else await page.keyboard.type(token); if (token === '/' || token === '?') await expect(page.locator('.practice-card .cm-editor input')).toBeFocused(); if (token === '<Enter>') await expect(page.locator('.practice-card .cm-content')).toBeFocused(); if (token === '<Esc>') await expect(page.getByTestId('placement-mode')).toHaveText('normal') } }
async function confirmCurrent(page: Page, tokens: string[]) { await command(page, tokens); await page.keyboard.press('Control+Enter'); await expect(page.getByTestId('placement-feedback')).toContainText('technique confirmed'); await page.keyboard.press('Control+Enter') }
async function dontKnow(page: Page, continueAfter = true) { await page.getByRole('button', { name: 'I don’t know' }).click(); await expect(page.getByTestId('placement-feedback')).toContainText('No problem'); if (continueAfter) await page.keyboard.press('Control+Enter') }
async function finishUnconfirmed(page: Page) { for (let index = 0; index < 6; index += 1) await dontKnow(page); await dontKnow(page, false); await page.keyboard.press('Control+Enter') }

test('welcome offers the unchanged beginning path and optional untimed placement', async ({ page }) => { await page.goto('./'); await expect(page.getByText(/about seven editing tasks/)).toBeVisible(); await page.getByRole('button', { name: /Start from the beginning/ }).click(); await expect(page.getByRole('heading', { name: 'Change inside quotes' })).toBeVisible(); const session = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).session); expect(session.exerciseIds).toHaveLength(7); expect(session.prescribed).toBe(true) })

test('placement preserves an unfinished session and exposes no teaching aids', async ({ page }) => { await page.goto('./#/practice'); const before = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).session); await openPlacement(page); await expect(page.getByRole('button', { name: /Hint|demonstration/i })).toHaveCount(0); await expect(page.getByText(/timing ignored/i)).toBeVisible(); await page.reload(); await expect(page.getByRole('heading', { name: 'Point at production' })).toBeVisible(); const after = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).session); expect(after).toEqual(before) })

test('reset restores a clean probe and correct alternatives remain unattributed', async ({ page }) => { await openPlacement(page); await page.keyboard.press('x'); await page.getByRole('button', { name: 'Reset task' }).click(); await command(page, ['c', 'i', '"', 'https://api.example.com', '<Esc>']); await page.getByRole('button', { name: 'Check', exact: false }).click(); await expect(page.getByTestId('placement-feedback')).toContainText('technique confirmed') })

test('repeated l can satisfy the movement outcome without f or t attribution', async ({ page }) => { await openPlacement(page); await page.getByRole('button', { name: 'I don’t know' }).click(); await page.getByRole('button', { name: 'Continue' }).click(); await command(page, Array(24).fill('l')); await page.getByRole('button', { name: 'Check', exact: false }).click(); await expect(page.getByTestId('placement-feedback')).toContainText('Outcome correct · technique not confirmed') })

test('seven unconfirmed probes finish nonpunitively with a Unit 1 recommendation', async ({ page }) => { await openPlacement(page); for (let index = 0; index < 7; index += 1) { await page.getByRole('button', { name: 'I don’t know' }).click(); await expect(page.getByTestId('placement-feedback')).toContainText('No problem'); await page.keyboard.press('Control+Enter') } await expect(page.getByRole('heading', { name: /Recommended starting point: Precise text objects/ })).toBeVisible(); await expect(page.getByText('Worth practicing')).toBeVisible(); const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!)); expect(stored.learner.attempts).toHaveLength(0); expect(stored.placement.results).toHaveLength(7) })

test('seven recognized probes recommend mixed adaptive review and seed provisional evidence', async ({ page }) => { await openPlacement(page); await confirmCurrent(page, ['c', 'i', '"', 'https://api.example.com', '<Esc>']); await confirmCurrent(page, ['t', ')']); await confirmCurrent(page, ['d', 'i', '(']); await confirmCurrent(page, ['f', ':', ';', ',']); await confirmCurrent(page, ['c', 't', ')', 'exponential', '<Esc>']); await confirmCurrent(page, ['c', 'i', 'w', 'warning', '<Esc>', '6', 'w', '.']); await command(page, ['/', 'staging', '<Enter>', 'c', 'i', 'w', 'production', '<Esc>', 'n', '.']); await page.keyboard.press('Control+Enter'); await expect(page.getByTestId('placement-feedback')).toContainText('technique confirmed'); await page.keyboard.press('Control+Enter'); await expect(page.getByRole('heading', { name: /Recommended starting point: Mixed adaptive review/ })).toBeVisible(); const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!)); expect(stored.learner.concepts['concept.inner-quotes']).toMatchObject({ strength: .6, confidence: .35 }); expect(stored.learner.attempts).toHaveLength(0) })

test('split Unit 1 evidence adds exactly one confirmation probe', async ({ page }) => { await openPlacement(page); await confirmCurrent(page, ['c', 'i', '"', 'https://api.example.com', '<Esc>']); for (let index = 0; index < 6; index += 1) { await page.getByRole('button', { name: 'I don’t know' }).click(); await page.keyboard.press('Control+Enter') } await expect(page.getByRole('heading', { name: 'Back off retries' })).toBeVisible(); await page.getByRole('button', { name: 'I don’t know' }).click(); await page.keyboard.press('Control+Enter'); const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!)); expect(stored.placement.results).toHaveLength(8) })

test('an all-unconfirmed recommendation starts the prescribed Unit 1 introduction', async ({ page }) => { await openPlacement(page); await finishUnconfirmed(page); await page.getByRole('button', { name: 'Start Precise text objects' }).click(); await expect(page.getByRole('heading', { name: 'Change inside quotes' })).toBeVisible(); const session = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).session); expect(session).toMatchObject({ prescribed: true, unitId: 'unit.precise-text-objects' }); expect(session.exerciseIds).toHaveLength(7) })

test('a Unit 2 recommendation initializes direct practice with its prescribed introduction', async ({ page }) => { await openPlacement(page); await confirmCurrent(page, ['c', 'i', '"', 'https://api.example.com', '<Esc>']); await dontKnow(page); await confirmCurrent(page, ['d', 'i', '(']); await dontKnow(page); await dontKnow(page); await dontKnow(page); await dontKnow(page, false); await page.keyboard.press('Control+Enter'); await expect(page.getByRole('heading', { name: /Recommended starting point: Target within a line/ })).toBeVisible(); await page.goto('./#/practice'); await expect(page.getByRole('heading', { name: 'Land on the assignment' })).toBeVisible(); const session = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).session); expect(session).toMatchObject({ prescribed: true, unitId: 'unit.line-targeting' }); expect(session.exerciseIds).toHaveLength(7) })

test('a completed placement summary and stored run survive refresh and revisit', async ({ page }) => { await openPlacement(page); await finishUnconfirmed(page); const before = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).placement); await page.reload(); await expect(page.getByRole('heading', { name: /Recommended starting point: Precise text objects/ })).toBeVisible(); await page.goto('./#/curriculum'); await page.goto('./#/placement'); await expect(page.getByRole('heading', { name: /Recommended starting point: Precise text objects/ })).toBeVisible(); expect(await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!).placement)).toEqual(before) })

test('explicit retake starts cleanly and preserves final-probe feedback before summary', async ({ page }) => { await openPlacement(page); await finishUnconfirmed(page); await page.getByRole('button', { name: 'Retake placement' }).click(); await expect(page.getByRole('heading', { name: 'Point at production' })).toBeVisible(); let stored = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!)); expect(stored.placement).toMatchObject({ status: 'active', results: [] }); for (let index = 0; index < 6; index += 1) await dontKnow(page); await dontKnow(page, false); await expect(page.getByTestId('placement-feedback')).toContainText('No problem'); await expect(page.getByRole('heading', { name: /Recommended starting point/ })).toHaveCount(0); await page.keyboard.press('Control+Enter'); await expect(page.getByRole('heading', { name: /Recommended starting point: Precise text objects/ })).toBeVisible(); stored = await page.evaluate(() => JSON.parse(localStorage.getItem('vim-xp-progress')!)); expect(stored.placement).toMatchObject({ status: 'completed' }); expect(stored.placement.results).toHaveLength(7) })
