import type { Concept, ConceptId, CurriculumUnit, DemonstrationStep, Exercise, ExerciseId } from '../model'

type Definition = { id: ExerciseId; variant: string; title: string; prompt: string; language: Exercise['initial']['language']; initial: string; cursor: number; tokens: string[]; final: string; finalCursor: number; primary: ConceptId; supporting: ConceptId[]; role: Exercise['role']; friction: Exercise['friction']; level: 1 | 2 | 3 }
const semantic = (tokens: string[]) => tokens.flatMap((token) => token.startsWith('<') ? [token] : [...token])
const step = (id: string, tokens: string[], display: 'key' | 'literal', title: string, explanation: string): DemonstrationStep => ({ id, tokens, display, title, explanation })
const stepsFor = (tokens: string[]): DemonstrationStep[] => tokens.map((token, index) => step(`step-${index + 1}`, [token], token.length > 1 && !token.startsWith('<') ? 'literal' : 'key', token === '.' ? 'Repeat the previous change' : token === '<Esc>' ? 'Return to Normal mode' : `Use ${token}`, token === '.' ? 'Press `.` to reproduce the last complete edit at the current target.' : token === '<Esc>' ? 'Press `Esc` so the edit is complete and ready to repeat.' : 'Apply the shown key as the next part of the workflow.'))
function make(def: Definition): Exercise { return { id: def.id, version: '1.0.0', variantGroupId: def.variant, title: def.title, prompt: def.prompt, initial: { document: def.initial, cursor: def.cursor, language: def.language, mode: 'normal' }, primaryConcepts: [def.primary], supportingConcepts: def.supporting, outcome: { type: 'all', rules: [{ type: 'exact-document', text: def.final }, ...(def.initial === def.final ? [{ type: 'cursor-at' as const, offset: def.finalCursor }] : []), { type: 'required-mode', mode: 'normal' }] }, strategies: [{ id: 'intended', label: def.tokens.join(''), trace: semantic(def.tokens), coaching: 'Correct. You moved deliberately and kept movement separate from repeating the completed change.', creditedConceptIds: [def.primary, ...def.supporting] }], hints: ['Identify whether this step needs movement to a target or repetition of an earlier change.', 'Use word motions and counts to travel; use dot only after a complete edit exists.', `Reproduce the workflow with ${def.tokens.join('')}.`, `Watch the workflow ${def.tokens.join('')} one step at a time, then reset and try it.`], referenceSolutions: [{ id: 'intended', tokens: def.tokens }], demonstration: { referenceSolutionId: 'intended', steps: stepsFor(def.tokens) }, difficulty: { level: def.level, estimatedMinutes: 1 }, friction: def.friction, role: def.role } }

const defs: Definition[] = [
  { id: 'exercise.move-word-cpp-next', variant: 'move-word-cpp-next', title: 'Move to the next setting', prompt: 'Move to the beginning of `timeout` without changing the declaration.', language: 'cpp', initial: 'auto retries = timeout + jitter;\n', cursor: 0, tokens: ['3', 'w'], final: 'auto retries = timeout + jitter;\n', finalCursor: 15, primary: 'concept.counted-motion', supporting: ['concept.word-forward', 'concept.normal-mode'], role: 'introduction', friction: 'low', level: 1 },
  { id: 'exercise.move-word-shell-back', variant: 'move-word-shell-back', title: 'Return to the variable', prompt: 'Move backward to the beginning of `BUILD_DIR` without changing the command.', language: 'shell', initial: 'cmake build BUILD_DIR parallel\n', cursor: 21, tokens: ['b'], final: 'cmake build BUILD_DIR parallel\n', finalCursor: 12, primary: 'concept.word-backward', supporting: ['concept.normal-mode'], role: 'introduction', friction: 'low', level: 1 },
  { id: 'exercise.move-word-cmake-end', variant: 'move-word-cmake-end', title: 'Reach the option boundary', prompt: 'Move to the end of `WARNINGS_AS_ERRORS` without changing the CMake line.', language: 'cmake', initial: 'option(WARNINGS_AS_ERRORS "Treat warnings as errors" ON)\n', cursor: 7, tokens: ['e'], final: 'option(WARNINGS_AS_ERRORS "Treat warnings as errors" ON)\n', finalCursor: 24, primary: 'concept.word-end', supporting: ['concept.normal-mode'], role: 'introduction', friction: 'low', level: 1 },
  { id: 'exercise.repeat-cpp-log-levels', variant: 'repeat-cpp-log-levels', title: 'Normalize two log levels', prompt: 'Change both `verbose` values to `warning`, making the edit once and reproducing it at the next value.', language: 'cpp', initial: 'client.level = verbose;\nserver.level = verbose;\n', cursor: 15, tokens: ['c', 'i', 'w', 'warning', '<Esc>', '6', 'w', '.'], final: 'client.level = warning;\nserver.level = warning;\n', finalCursor: 46, primary: 'concept.dot-repeat', supporting: ['concept.inner-word', 'concept.counted-motion', 'concept.normal-mode'], role: 'introduction', friction: 'medium', level: 2 },
  { id: 'exercise.repeat-shell-modes', variant: 'repeat-shell-modes', title: 'Promote two modes', prompt: 'Change both `staging` values to `production` by completing one edit, moving, and repeating it.', language: 'shell', initial: 'BUILD_MODE=staging\nDEPLOY_MODE=staging\n', cursor: 11, tokens: ['c', 'i', 'w', 'production', '<Esc>', '3', 'w', '.'], final: 'BUILD_MODE=production\nDEPLOY_MODE=production\n', finalCursor: 43, primary: 'concept.dot-repeat', supporting: ['concept.inner-word', 'concept.word-forward', 'concept.normal-mode'], role: 'introduction', friction: 'medium', level: 2 },
  { id: 'exercise.repeat-cmake-features', variant: 'repeat-cmake-features', title: 'Enable paired features', prompt: 'Change both `OFF` values to `ON`, repeating the completed edit at the second option.', language: 'cmake', initial: 'set(FEATURE_CACHE OFF)\nset(FEATURE_LOGS OFF)\n', cursor: 18, tokens: ['c', 'i', 'w', 'ON', '<Esc>', '5', 'w', '.'], final: 'set(FEATURE_CACHE ON)\nset(FEATURE_LOGS ON)\n', finalCursor: 41, primary: 'concept.dot-repeat', supporting: ['concept.inner-word', 'concept.counted-motion', 'concept.normal-mode'], role: 'transfer', friction: 'medium', level: 2 },
  { id: 'exercise.repeat-cpp-arguments', variant: 'repeat-cpp-arguments', title: 'Update repeated arguments', prompt: 'Change both `primary` arguments to `replica`, making the change once and reproducing it.', language: 'cpp', initial: 'connect(primary);\nmonitor(primary);\n', cursor: 8, tokens: ['c', 'i', 'w', 'replica', '<Esc>', '4', 'w', '.'], final: 'connect(replica);\nmonitor(replica);\n', finalCursor: 32, primary: 'concept.dot-repeat', supporting: ['concept.inner-word', 'concept.counted-motion', 'concept.normal-mode'], role: 'transfer', friction: 'high', level: 3 },
  { id: 'exercise.move-word-shell-end', variant: 'move-word-shell-end', title: 'Inspect the final path segment', prompt: 'Move to the end of `artifacts` without changing the upload command.', language: 'shell', initial: 'upload build release artifacts\n', cursor: 0, tokens: ['4', 'e'], final: 'upload build release artifacts\n', finalCursor: 29, primary: 'concept.word-end', supporting: ['concept.counted-motion', 'concept.normal-mode'], role: 'reinforcement', friction: 'low', level: 1 },
  { id: 'exercise.repeat-cmake-targets', variant: 'repeat-cmake-targets', title: 'Rename paired targets', prompt: 'Rename both `legacy` targets to `modern` using one edit and one repeat.', language: 'cmake', initial: 'add_library(legacy core.cpp)\ntarget_link_libraries(legacy PRIVATE base)\n', cursor: 12, tokens: ['c', 'i', 'w', 'modern', '<Esc>', '7', 'w', '.'], final: 'add_library(modern core.cpp)\ntarget_link_libraries(modern PRIVATE base)\n', finalCursor: 52, primary: 'concept.dot-repeat', supporting: ['concept.inner-word', 'concept.counted-motion', 'concept.normal-mode'], role: 'review', friction: 'high', level: 3 },
  { id: 'exercise.move-word-cpp-back', variant: 'move-word-cpp-back', title: 'Return to the policy name', prompt: 'Move backward to the beginning of `retry_policy` without editing the line.', language: 'cpp', initial: 'configure(worker_count, retry_policy, timeout);\n', cursor: 40, tokens: ['3', 'b'], final: 'configure(worker_count, retry_policy, timeout);\n', finalCursor: 24, primary: 'concept.word-backward', supporting: ['concept.counted-motion', 'concept.normal-mode'], role: 'review', friction: 'low', level: 1 },
]
export const moveAndRepeatExercises = defs.map(make)
export const moveAndRepeatConcepts: Concept[] = [
  { id: 'concept.word-forward', version: '1.0.0', title: 'Next word', summary: 'Move to the beginning of a later word.' }, { id: 'concept.word-backward', version: '1.0.0', title: 'Previous word', summary: 'Move to the beginning of an earlier word.' }, { id: 'concept.word-end', version: '1.0.0', title: 'Word end', summary: 'Move to the end of a word.' }, { id: 'concept.counted-motion', version: '1.0.0', title: 'Counted movement', summary: 'Use a useful count with a motion.' }, { id: 'concept.dot-repeat', version: '1.0.0', title: 'Repeat a change', summary: 'Reproduce the previous completed change with dot.' },
]
export const moveAndRepeatUnit: CurriculumUnit = { id: 'unit.move-and-repeat', version: '1.0.0', order: 3, title: 'Move and repeat', summary: 'Navigate by words, use useful counts, and reproduce complete edits.', description: 'Separate movement from change repetition, then combine earlier targeting skills with dot in realistic workflows.', conceptIds: moveAndRepeatConcepts.map((item) => item.id), exerciseIds: moveAndRepeatExercises.map((item) => item.id), recommendedPrerequisiteUnitIds: ['unit.precise-text-objects', 'unit.line-targeting'], prescribedExerciseIds: defs.slice(0, 7).map((item) => item.id), completionCopy: 'Move-and-repeat session complete.' }
