import type { Concept, ConceptId, CurriculumUnit, DemonstrationStep, Exercise, ExerciseId } from '../model'
type Definition = { id: ExerciseId; variant: string; title: string; prompt: string; language: Exercise['initial']['language']; initial: string; cursor: number; tokens: string[]; final: string; finalCursor: number; primary: ConceptId; supporting: ConceptId[]; role: Exercise['role']; friction: Exercise['friction']; level: 1 | 2 | 3 }
const semantic = (tokens: string[]) => tokens.flatMap((token) => token.startsWith('<') ? [token] : [...token])
const stepsFor = (tokens: string[]): DemonstrationStep[] => tokens.map((token, index) => ({ id: `step-${index + 1}`, tokens: [token], display: token.length > 1 && !token.startsWith('<') ? 'literal' : 'key', title: token === '<Enter>' ? 'Run the search' : token === 'n' ? 'Continue the search' : token === '.' ? 'Repeat the completed edit' : `Use ${token}`, explanation: token === '<Enter>' ? 'Press `Enter` to move to the matching text.' : token === 'n' ? 'Press `n` to continue in the active search direction.' : token === '.' ? 'Press `.` to reproduce the last completed change here.' : 'Apply the shown key as the next part of the search workflow.' }))
function make(def: Definition): Exercise { return { id: def.id, version: '1.0.0', variantGroupId: def.variant, title: def.title, prompt: def.prompt, initial: { document: def.initial, cursor: def.cursor, language: def.language, mode: 'normal' }, primaryConcepts: [def.primary], supportingConcepts: def.supporting, outcome: { type: 'all', rules: [{ type: 'exact-document', text: def.final }, ...(def.initial === def.final ? [{ type: 'cursor-at' as const, offset: def.finalCursor }] : []), { type: 'required-mode', mode: 'normal' }] }, strategies: [{ id: 'intended', label: def.tokens.join(''), trace: semantic(def.tokens), coaching: 'Correct. Search moved between repeated content, while the edit and dot repeat remained separate actions.', creditedConceptIds: [def.primary, ...def.supporting] }], hints: ['Find the repeated text directly instead of crossing the file one motion at a time.', 'Start a search, continue in its active direction, and repeat a change only after completing it.', `Use the workflow ${def.tokens.join('')}.`, `Watch ${def.tokens.join('')} execute one step at a time, then reset and reproduce it.`], referenceSolutions: [{ id: 'intended', tokens: def.tokens }], demonstration: { referenceSolutionId: 'intended', steps: stepsFor(def.tokens) }, difficulty: { level: def.level, estimatedMinutes: 1 }, friction: def.friction, role: def.role } }
const defs: Definition[] = [
  { id: 'exercise.search-cpp-worker', variant: 'search-cpp-worker', title: 'Find the worker configuration', prompt: 'Move to `worker_count` in the later configuration line without changing the file.', language: 'cpp', initial: '// defaults\nauto count = 4;\nconfigure(worker_count, count);\n', cursor: 0, tokens: ['/', 'worker_count', '<Enter>'], final: '// defaults\nauto count = 4;\nconfigure(worker_count, count);\n', finalCursor: 38, primary: 'concept.search-forward', supporting: ['concept.normal-mode'], role: 'introduction', friction: 'low', level: 1 },
  { id: 'exercise.search-shell-next-service', variant: 'search-shell-next-service', title: 'Visit the second service', prompt: 'Move to the second occurrence of `service` without editing the script.', language: 'shell', initial: 'check service_api\ncheck service_worker\ncheck service_jobs\n', cursor: 0, tokens: ['/', 'service', '<Enter>', 'n'], final: 'check service_api\ncheck service_worker\ncheck service_jobs\n', finalCursor: 24, primary: 'concept.search-next', supporting: ['concept.search-forward', 'concept.normal-mode'], role: 'introduction', friction: 'low', level: 1 },
  { id: 'exercise.search-cmake-previous-target', variant: 'search-cmake-previous-target', title: 'Continue to the linked target', prompt: 'Find the later `worker` reference without changing the build file.', language: 'cmake', initial: 'add_executable(worker main.cpp)\ntarget_link_libraries(worker PRIVATE core)\n', cursor: 0, tokens: ['/', 'worker', '<Enter>', 'n'], final: 'add_executable(worker main.cpp)\ntarget_link_libraries(worker PRIVATE core)\n', finalCursor: 54, primary: 'concept.search-next', supporting: ['concept.search-forward', 'concept.normal-mode'], role: 'introduction', friction: 'medium', level: 2 },
  { id: 'exercise.search-shell-backward-mode', variant: 'search-shell-backward-mode', title: 'Find the deployment mode', prompt: 'Move directly to `DEPLOY_MODE` without changing the script.', language: 'shell', initial: 'BUILD_MODE=release\nDEPLOY_MODE=release\nrun "$DEPLOY_MODE"\n', cursor: 0, tokens: ['/', 'DEPLOY_MODE', '<Enter>'], final: 'BUILD_MODE=release\nDEPLOY_MODE=release\nrun "$DEPLOY_MODE"\n', finalCursor: 19, primary: 'concept.search-forward', supporting: ['concept.normal-mode'], role: 'introduction', friction: 'medium', level: 2 },
  { id: 'exercise.search-act-cpp-staging', variant: 'search-act-cpp-staging', title: 'Promote repeated environments', prompt: 'Change both `staging` values to `production` using search to reach them and repeating the completed edit.', language: 'cpp', initial: 'client.env = staging;\nserver.env = staging;\n', cursor: 0, tokens: ['/', 'staging', '<Enter>', 'c', 'i', 'w', 'production', '<Esc>', 'n', '.'], final: 'client.env = production;\nserver.env = production;\n', finalCursor: 48, primary: 'concept.search-repeat-edit', supporting: ['concept.search-forward', 'concept.search-next', 'concept.dot-repeat', 'concept.inner-word', 'concept.normal-mode'], role: 'introduction', friction: 'high', level: 3 },
  { id: 'exercise.search-act-cmake-off', variant: 'search-act-cmake-off', title: 'Enable repeated options', prompt: 'Change both `OFF` settings to `ON` by searching for the setting and repeating one completed edit.', language: 'cmake', initial: 'set(CACHE OFF)\nset(LOGS OFF)\n', cursor: 0, tokens: ['/', 'OFF', '<Enter>', 'c', 'i', 'w', 'ON', '<Esc>', 'n', '.'], final: 'set(CACHE ON)\nset(LOGS ON)\n', finalCursor: 25, primary: 'concept.search-repeat-edit', supporting: ['concept.search-forward', 'concept.search-next', 'concept.dot-repeat', 'concept.inner-word', 'concept.normal-mode'], role: 'transfer', friction: 'medium', level: 2 },
  { id: 'exercise.search-act-shell-hosts', variant: 'search-act-shell-hosts', title: 'Update repeated hosts', prompt: 'Change both `oldhost` values to `newhost` using search and one repeated edit.', language: 'shell', initial: 'PRIMARY=oldhost\nSECONDARY=oldhost\n', cursor: 0, tokens: ['/', 'oldhost', '<Enter>', 'c', 'i', 'w', 'newhost', '<Esc>', 'n', '.'], final: 'PRIMARY=newhost\nSECONDARY=newhost\n', finalCursor: 33, primary: 'concept.search-repeat-edit', supporting: ['concept.search-forward', 'concept.search-next', 'concept.dot-repeat', 'concept.inner-word', 'concept.normal-mode'], role: 'transfer', friction: 'high', level: 3 },
  { id: 'exercise.search-cpp-third-retry', variant: 'search-cpp-third-retry', title: 'Inspect the third retry branch', prompt: 'Move directly to the third `retry` occurrence without editing the file.', language: 'cpp', initial: 'if (retry) first();\nif (retry) second();\nif (retry) third();\n', cursor: 0, tokens: ['/', 'retry', '<Enter>', '2', 'n'], final: 'if (retry) first();\nif (retry) second();\nif (retry) third();\n', finalCursor: 45, primary: 'concept.search-next', supporting: ['concept.search-forward', 'concept.counted-motion', 'concept.normal-mode'], role: 'reinforcement', friction: 'low', level: 2 },
  { id: 'exercise.search-cmake-return-library', variant: 'search-cmake-return-library', title: 'Continue through library references', prompt: 'Find the third `core` reference without changing the build file.', language: 'cmake', initial: 'add_library(core core.cpp)\ntarget_link_libraries(app PRIVATE core)\ninstall(TARGETS core)\n', cursor: 0, tokens: ['/', 'core', '<Enter>', '2', 'n'], final: 'add_library(core core.cpp)\ntarget_link_libraries(app PRIVATE core)\ninstall(TARGETS core)\n', finalCursor: 61, primary: 'concept.search-next', supporting: ['concept.search-forward', 'concept.counted-motion', 'concept.normal-mode'], role: 'review', friction: 'medium', level: 2 },
  { id: 'exercise.search-act-cpp-flags', variant: 'search-act-cpp-flags', title: 'Retire repeated flags', prompt: 'Change both `legacy_flag` occurrences to `modern_flag` through search and repeat.', language: 'cpp', initial: 'enable(legacy_flag);\nverify(legacy_flag);\n', cursor: 0, tokens: ['/', 'legacy_flag', '<Enter>', 'c', 'i', 'w', 'modern_flag', '<Esc>', 'n', '.'], final: 'enable(modern_flag);\nverify(modern_flag);\n', finalCursor: 40, primary: 'concept.search-repeat-edit', supporting: ['concept.search-forward', 'concept.search-next', 'concept.dot-repeat', 'concept.inner-word', 'concept.normal-mode'], role: 'review', friction: 'high', level: 3 },
]
export const searchAndActExercises = defs.map(make)
export const searchAndActConcepts: Concept[] = [{ id: 'concept.search-forward', version: '1.0.0', title: 'Forward search', summary: 'Search forward for text in the file.' }, { id: 'concept.search-next', version: '1.0.0', title: 'Next match', summary: 'Continue to later matches in the current search.' }, { id: 'concept.search-repeat-edit', version: '1.0.0', title: 'Search and repeat edits', summary: 'Combine search navigation with a repeatable change.' }]
export const searchAndActUnit: CurriculumUnit = { id: 'unit.search-and-act', version: '1.0.0', order: 4, title: 'Search and act', summary: 'Navigate repeated content with search and apply repeatable changes.', description: 'Use forward search, visit later matches, and combine search with earlier editing skills across a file.', conceptIds: searchAndActConcepts.map((item) => item.id), exerciseIds: searchAndActExercises.map((item) => item.id), recommendedPrerequisiteUnitIds: ['unit.precise-text-objects', 'unit.move-and-repeat'], prescribedExerciseIds: defs.slice(0, 7).map((item) => item.id), completionCopy: 'Search-and-act session complete.' }
