import { describe, expect, it } from 'vitest'
import { curriculum } from '../content/curriculum'
import { recognizeStrategy } from '../content/strategy'
import { emptyLearnerState } from './learnerModel'
import { applyPlacementEvidence, emptyPlacementRun, nextPlacementGate, placementRecommendation, recordPlacementResult } from './placement'

const result = (gateId: string, outcome: 'confirmed' | 'correct-unattributed' | 'unconfirmed' = 'confirmed') => { const gate = curriculum.placementGates.find((item) => item.id === gateId)!; return { gateId, exerciseId: gate.exerciseId, unitId: gate.unitId, outcome, strategyId: outcome === 'confirmed' ? gate.acceptedStrategyIds[0] : undefined, completedAt: 100 } }
const runResults = (outcomes: Array<'confirmed' | 'correct-unattributed' | 'unconfirmed'>) => { let run = emptyPlacementRun('run', 1); for (const [index, gate] of curriculum.placementGates.filter((item) => item.role === 'required').sort((a, b) => a.priority - b.priority).entries()) run = recordPlacementResult(curriculum, emptyLearnerState(), run, result(gate.id, outcomes[index] ?? 'confirmed')); return run }

describe('placement', () => {
  it('recognizes exact strategies without confusing repeated movement', () => { const exercise = curriculum.exercises.find((item) => item.id === 'exercise.line-till-cpp-close-paren')!; expect(recognizeStrategy(exercise, ['t', ')'])?.id).toBe('intended'); expect(recognizeStrategy(exercise, Array(15).fill('l'))).toBeUndefined() })
  it('uses the deterministic seven-gate sequence without repeats', () => { const ids: string[] = []; let run = emptyPlacementRun('run', 1); while (nextPlacementGate(curriculum, run)) { const gate = nextPlacementGate(curriculum, run)!; ids.push(gate.id); run = recordPlacementResult(curriculum, emptyLearnerState(), run, result(gate.id)) } expect(ids).toEqual(['gate.precise-quotes', 'gate.line-movement', 'gate.precise-parens', 'gate.line-repeat-reverse', 'gate.line-operator', 'gate.move-repeat', 'gate.search-act']); expect(new Set(ids).size).toBe(ids.length); expect(run.status).toBe('completed') })
  it('adds confirmation only for split Unit 1 results', () => { const split = runResults(['confirmed', 'confirmed', 'unconfirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed']); expect(nextPlacementGate(curriculum, split)?.id).toBe('gate.precise-confirmation'); const bothMissed = runResults(['unconfirmed', 'confirmed', 'unconfirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed']); expect(nextPlacementGate(curriculum, bothMissed)).toBeUndefined() })
  it('produces every recommendation outcome', () => { expect(placementRecommendation(curriculum, emptyLearnerState(), runResults(['unconfirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed']))).toMatchObject({ kind: 'unit', unitId: 'unit.precise-text-objects' }); expect(placementRecommendation(curriculum, emptyLearnerState(), runResults(['confirmed', 'unconfirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed']))).toMatchObject({ kind: 'unit', unitId: 'unit.line-targeting' }); expect(placementRecommendation(curriculum, emptyLearnerState(), runResults(['confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'unconfirmed', 'confirmed']))).toMatchObject({ kind: 'unit', unitId: 'unit.move-and-repeat' }); expect(placementRecommendation(curriculum, emptyLearnerState(), runResults(['confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'unconfirmed']))).toMatchObject({ kind: 'unit', unitId: 'unit.search-and-act' }); expect(placementRecommendation(curriculum, emptyLearnerState(), runResults(Array(7).fill('confirmed') as 'confirmed'[]))).toMatchObject({ kind: 'adaptive-review' }) })
  it('applies provisional floors once without attempts or evidence reduction', () => { const complete = runResults(Array(5).fill('confirmed') as 'confirmed'[]); const learner = emptyLearnerState(); learner.concepts['concept.inner-quotes'] = { strength: .9, confidence: .8, successes: 3, exposures: 4, variants: [], lastSeenAt: 200, dueAt: 999999999, recentExerciseIds: [] }; const applied = applyPlacementEvidence(curriculum, learner, complete); expect(applied.learner.attempts).toEqual([]); expect(applied.learner.concepts['concept.inner-quotes']).toMatchObject({ strength: .9, confidence: .8, successes: 3, exposures: 4, dueAt: 999999999 }); expect(applied.learner.concepts['concept.inner-parentheses']).toMatchObject({ strength: .6, confidence: .35, successes: 1, exposures: 1 }); expect(applyPlacementEvidence(curriculum, applied.learner, applied.run)).toEqual(applied) })
  it('does not apply unattributed or unconfirmed evidence', () => { const complete = runResults(['correct-unattributed', 'confirmed', 'unconfirmed', 'confirmed', 'confirmed']); const applied = applyPlacementEvidence(curriculum, emptyLearnerState(), complete); expect(applied.learner.concepts['concept.inner-quotes']).toBeUndefined(); expect(applied.learner.concepts['concept.inner-parentheses']).toBeUndefined() })
})
