import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { curriculum, getExercise, getUnit } from '../content/curriculum'
import { evaluateOutcome } from '../content/evaluator'
import { parseInlineMarkup } from '../content/inlineMarkup'
import { recognizeStrategy } from '../content/strategy'
import type { Exercise } from '../content/model'
import type { EditorSnapshot, VimEditorAdapter } from '../editor/VimEditorAdapter'
import { applyPlacementEvidence, confirmedConceptIds, emptyPlacementRun, nextPlacementGate, recordPlacementResult, type PlacementOutcome } from '../learning/placement'
import { createProgressStore, type StoredProgress } from '../learning/persistence'
import { planSession } from '../learning/planner'
import { ProductNav } from './ProductNav'
import { VimEditor } from './VimEditor'

const initialSnapshot = (exercise: Exercise): EditorSnapshot => ({ document: exercise.initial.document, cursor: exercise.initial.cursor, selection: { from: exercise.initial.cursor, to: exercise.initial.cursor }, mode: 'normal', trace: [] })
function Inline({ text }: { text: string }) { return <>{parseInlineMarkup(text).map((part, index) => <Fragment key={index}>{part.type === 'code' ? <code>{part.value}</code> : part.value}</Fragment>)}</> }

export function PlacementScreen() {
  const store = useMemo(() => createProgressStore(localStorage, curriculum.version, curriculum.exercises.map((item) => item.id), curriculum.units.map((unit) => unit.id), curriculum.placementGates.map((gate) => gate.id)), [])
  const [progress, setProgress] = useState<StoredProgress>(() => { const loaded = store.load(); if (loaded.placement) return loaded; const now = Date.now(); const run = emptyPlacementRun(`placement-${now}`, now); return { ...loaded, placement: { ...run, currentGateId: nextPlacementGate(curriculum, run)?.id } } })
  const persistedRun = progress.placement!
  const [summaryRunId, setSummaryRunId] = useState(persistedRun.status === 'completed' ? persistedRun.runId : '')
  const run = useMemo(() => persistedRun.status === 'completed' && summaryRunId !== persistedRun.runId ? { ...persistedRun, status: 'active' as const, currentGateId: persistedRun.results.at(-1)?.gateId } : persistedRun, [persistedRun, summaryRunId])
  const gateId = run.status === 'active' ? (run.currentGateId ?? nextPlacementGate(curriculum, run)?.id) : run.results.at(-1)?.gateId
  const gate = curriculum.placementGates.find((item) => item.id === gateId)
  const exercise = gate ? getExercise(gate.exerciseId)! : undefined
  const [generation, setGeneration] = useState(0); const [snapshot, setSnapshot] = useState<EditorSnapshot>(() => initialSnapshot(exercise ?? curriculum.exercises[0])); const [resolved, setResolved] = useState<PlacementOutcome | null>(null); const [message, setMessage] = useState('Make the requested change, then check when you are ready.'); const adapterRef = useRef<VimEditorAdapter | null>(null)
  useEffect(() => store.save(progress), [progress, store])
  const reset = useCallback(() => { if (!exercise || resolved) return; setSnapshot(initialSnapshot(exercise)); setMessage('Task reset. Timing is ignored.'); setGeneration((value) => value + 1) }, [exercise, resolved])
  const resolve = useCallback((outcome: PlacementOutcome, strategyId?: string) => { if (!gate || !exercise || resolved) return; const now = Date.now(); const updated = recordPlacementResult(curriculum, progress.learner, run, { gateId: gate.id, exerciseId: exercise.id, unitId: gate.unitId, outcome, strategyId, completedAt: now }); const applied = updated.status === 'completed' ? applyPlacementEvidence(curriculum, progress.learner, updated) : { learner: progress.learner, run: updated }; setProgress({ ...progress, learner: applied.learner, placement: applied.run }); setResolved(outcome) }, [exercise, gate, progress, resolved, run])
  const check = useCallback(() => { if (!exercise || !gate || resolved) return; const current = adapterRef.current?.snapshot() ?? snapshot; const evaluation = evaluateOutcome(exercise.outcome, current); if (!evaluation.passed) { resolve('unconfirmed'); setMessage(evaluation.issues.some((issue) => issue.type === 'cursor-mismatch') ? 'The cursor has not reached the requested destination. We’ll include this material in your path.' : 'The editor does not match the requested outcome yet. We’ll include this material in your path.'); return } const strategy = recognizeStrategy(exercise, current.trace, gate.acceptedStrategyIds); if (strategy) { resolve('confirmed', strategy.id); setMessage('Outcome correct · technique confirmed') } else { resolve('correct-unattributed'); setMessage('Outcome correct · technique not confirmed. The result counts as correct, but placement cannot use it to skip technique instruction.') } }, [exercise, gate, resolve, resolved, snapshot])
  const dontKnow = () => { resolve('unconfirmed'); setMessage('No problem—we’ll include this material in your recommended path.') }
  const next = () => { if (!resolved) return; if (progress.placement?.status === 'completed') { setSummaryRunId(progress.placement.runId); return } const nextGate = nextPlacementGate(curriculum, progress.placement!); setResolved(null); setMessage('Make the requested change, then check when you are ready.'); if (nextGate) { setProgress({ ...progress, placement: { ...progress.placement!, currentGateId: nextGate.id } }); setSnapshot(initialSnapshot(getExercise(nextGate.exerciseId)!)); setGeneration((value) => value + 1) } }
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.ctrlKey && event.key === 'Enter') { event.preventDefault(); if (resolved) next(); else check() } }; window.addEventListener('keydown', listener, true); return () => window.removeEventListener('keydown', listener, true) })
  const startRecommendation = () => { const recommendation = run.recommendation!; if (progress.session && !progress.session.completed && !window.confirm('Replace your unfinished practice session? Completed work will remain saved.')) return; const now = Date.now(); const focus = recommendation.kind === 'unit' ? recommendation.unitId : undefined; const plan = planSession(curriculum, progress.learner, { now: () => now }, (now + progress.learner.attempts.length) >>> 0, false, progress.recentVariants, focus, recommendation.kind === 'adaptive-review'); store.save({ ...progress, session: { ...plan, index: 0, completed: false } }); window.location.hash = '#/practice' }
  if (run.status === 'completed') { const recommendation = run.recommendation!; const confirmed = confirmedConceptIds(curriculum, run); const unattributed = run.results.filter((item) => item.outcome === 'correct-unattributed'); const worth = curriculum.placementGates.filter((item) => item.role === 'required' && !run.results.some((result) => result.gateId === item.id && result.outcome === 'confirmed')).flatMap((item) => item.conceptIds); const title = recommendation.kind === 'adaptive-review' ? 'Mixed adaptive review' : getUnit(recommendation.unitId)!.title; return <main className="placement-screen"><ProductNav /><section className="completion-card"><p className="lesson-label">Placement complete</p><h1>Recommended starting point: {title}</h1><p>{recommendation.reason}</p><h2>Techniques we could confirm</h2><ul>{confirmed.map((id) => <li key={id}>{curriculum.concepts.find((item) => item.id === id)?.title}</li>)}</ul><h2>Worth practicing</h2><ul>{[...new Set(worth)].map((id) => <li key={id}>{curriculum.concepts.find((item) => item.id === id)?.title}</li>)}</ul>{unattributed.length > 0 && <><h2>Correct outcomes without technique attribution</h2><p>You reached these requested results, but placement could not confirm the specific Vim technique: {unattributed.map((item) => getExercise(item.exerciseId)?.title).join(', ')}.</p></>}<div className="completion-actions"><button className="primary" onClick={startRecommendation}>Start {title}</button><a href="#/curriculum">View curriculum</a><button onClick={() => { const now = Date.now(); const fresh = emptyPlacementRun(`placement-${now}`, now); setProgress({ ...progress, placement: { ...fresh, currentGateId: nextPlacementGate(curriculum, fresh)?.id } }); setResolved(null) }}>Retake placement</button>{progress.session && !progress.session.completed && <a href="#/practice">Resume previous session</a>}</div></section></main> }
  if (!exercise || !gate) return null
  const editorInitial = { text: exercise.initial.document, cursor: exercise.initial.cursor, selection: exercise.initial.selection, language: exercise.initial.language }
  return <main className="placement-screen"><ProductNav /><div className="session-progress"><div><span>Placement</span><strong>{run.results.length + 1} of about 5</strong></div></div><header className="practice-header"><p className="lesson-label">Focused diagnostic · timing ignored</p><h1>{exercise.title}</h1><p className="goal"><Inline text={exercise.prompt} /></p></header><section className="practice-card"><div className="editor-bar"><h2>{exercise.initial.language} editing task</h2><span className="mode-pill">Mode: <strong data-testid="placement-mode">{snapshot.mode}</strong></span></div><VimEditor initial={editorInitial} generation={generation} adapterRef={adapterRef} onChange={setSnapshot} /><div className="practice-actions"><button onClick={reset} disabled={Boolean(resolved)}>Reset task</button><button className="skip" onClick={dontKnow} disabled={Boolean(resolved)}>I don’t know</button><a className="exit-placement" href="#/welcome">Exit placement</a><button className="primary" onClick={resolved ? next : check}>{resolved ? 'Continue' : <>Check <kbd>Ctrl</kbd>+<kbd>Enter</kbd></>}</button></div></section><section className={`feedback ${resolved === 'confirmed' ? 'success' : ''}`} data-testid="placement-feedback" aria-live="polite"><p>{message}</p></section></main>
}
